#!/usr/bin/env node
/** Build a deterministic, source-only ZIP for GoDaddy Node.js Hosting. */
import { createHash } from "node:crypto";
import { lstat, mkdir, readFile, readdir, rename, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { deflateRawSync } from "node:zlib";

const root = process.cwd();
const outputDirectory = path.join(root, "release-artifacts");
const outputPath = path.join(outputDirectory, "ship-print-esell-godaddy-node24.zip");
const temporaryPath = `${outputPath}.tmp`;
const fixedDosDate = 0x0021; // 1980-01-01
const fixedDosTime = 0x0000;

// Keep this an explicit source allowlist. New local files are excluded until a
// maintainer deliberately identifies them as runtime/build/operations inputs.
const rootFiles = [
  ".env.example",
  "DEPLOYMENT-HANDBOOK.md",
  "DEPLOYMENT.md",
  "README.md",
  "next.config.ts",
  "package-lock.json",
  "package.json",
  "tsconfig.json",
];
const sourceDirectories = ["db", "public", "src"];
const operationsFiles = [
  "scripts/backup.mjs",
  "scripts/backup.sh",
  "scripts/create-owner.mjs",
  "scripts/init-db.mjs",
  "scripts/maintenance.mjs",
  "scripts/package-godaddy.mjs",
];
const databaseImportPath = "db/godaddy-import.sql";
const databaseInitializationFiles = [
  "db/schema.sql",
  "db/migrations/001-minimum-order-total.sql",
  "db/migrations/002-same-day-release.sql",
  "db/migrations/003-delivery-hardening.sql",
  "db/seed-required-catalog.sql",
  "db/seed-pricing-details.sql",
];

const forbiddenParts = new Set([
  ".artifacts", ".git", ".local-data", ".local-test-db", ".next", ".next-build-check",
  ".next-verify", ".openclaw", ".vercel", ".visual", "build", "coverage", "dist",
  "logs", "node_modules", "out", "playwright-report", "release-artifacts", "test-results",
  "tests", "uploads",
]);
const forbiddenNames = new Set([
  ".npmrc", "credentials.json", "playwright.config.ts", "tokens.json", "vitest.config.ts",
]);
const secretExtensions = new Set([".key", ".p12", ".pem", ".pfx"]);
const deploymentUnusedFiles = new Set([
  "public/globe.svg",
  "public/next.svg",
  "public/window.svg",
  "public/figma/ship-print-esell-logo.png",
  "src/app/shipesel.jpg",
]);

function forbiddenReason(relativePath) {
  const parts = relativePath.split("/");
  const name = parts.at(-1) ?? "";
  if (parts.some((part) => forbiddenParts.has(part))) return "forbidden directory";
  if (name.startsWith(".env") && relativePath !== ".env.example") return "environment file";
  if (forbiddenNames.has(name)) return "test or credential configuration";
  if (deploymentUnusedFiles.has(relativePath)) return "unused source asset";
  if (path.extname(name).toLowerCase() === ".ai") return "editor source file";
  if (/\.(?:test|spec)\.[cm]?[jt]sx?$/.test(name) || name === "__snapshots__") return "test source";
  if (/\.(?:log|tsbuildinfo)$/.test(name)) return "log or cache";
  if (secretExtensions.has(path.extname(name).toLowerCase())) return "private-key container";
  if (/^(?:credentials|tokens|service-account)(?:[._-].*)?\.json$/i.test(name)) return "credential file";
  return null;
}

function comparePaths(left, right) {
  return Buffer.compare(Buffer.from(left, "utf8"), Buffer.from(right, "utf8"));
}

async function collectDirectory(relativeDirectory) {
  const absoluteDirectory = path.join(root, relativeDirectory);
  const entries = await readdir(absoluteDirectory, { withFileTypes: true });
  const files = [];
  for (const entry of entries.sort((a, b) => comparePaths(a.name, b.name))) {
    const relativePath = `${relativeDirectory}/${entry.name}`;
    if (forbiddenReason(relativePath)) continue;
    if (entry.isSymbolicLink()) throw new Error(`Refusing to package symbolic link: ${relativePath}`);
    if (entry.isDirectory()) files.push(...await collectDirectory(relativePath));
    else if (entry.isFile()) files.push(relativePath);
  }
  return files;
}

async function collectFiles() {
  const files = [...rootFiles, ...operationsFiles];
  for (const directory of sourceDirectories) files.push(...await collectDirectory(directory));
  files.push(databaseImportPath);
  return [...new Set(files)].sort(comparePaths);
}

async function generatedEntries() {
  const sections = [
    "-- Ship Print eSell — GoDaddy one-step MySQL 8 import.\n-- Generated by npm run package:godaddy; do not edit this archive copy.\n",
  ];
  for (const file of databaseInitializationFiles) {
    sections.push(`\n-- BEGIN ${file}\n`, await readFile(path.join(root, file), "utf8"), `\n-- END ${file}\n`);
  }
  return new Map([[databaseImportPath, Buffer.from(sections.join(""), "utf8")]]);
}

const crcTable = Array.from({ length: 256 }, (_, value) => {
  let crc = value;
  for (let bit = 0; bit < 8; bit += 1) crc = (crc >>> 1) ^ ((crc & 1) ? 0xedb88320 : 0);
  return crc >>> 0;
});
function crc32(buffer) {
  let crc = 0xffffffff;
  for (const byte of buffer) crc = (crc >>> 8) ^ crcTable[(crc ^ byte) & 0xff];
  return (crc ^ 0xffffffff) >>> 0;
}
function u16(value) { const buffer = Buffer.alloc(2); buffer.writeUInt16LE(value); return buffer; }
function u32(value) { const buffer = Buffer.alloc(4); buffer.writeUInt32LE(value >>> 0); return buffer; }

function normalizedMode(relativePath) {
  return relativePath.startsWith("scripts/") ? 0o100755 : 0o100644;
}

async function buildZip(files, generated) {
  const localParts = [];
  const centralParts = [];
  let offset = 0;
  for (const relativePath of files) {
    const reason = forbiddenReason(relativePath);
    if (reason) throw new Error(`Refusing forbidden package entry (${reason}): ${relativePath}`);
    const absolutePath = path.join(root, relativePath);
    const data = generated.get(relativePath) ?? await (async () => {
      const metadata = await lstat(absolutePath);
      if (!metadata.isFile()) throw new Error(`Required package entry is not a regular file: ${relativePath}`);
      return readFile(absolutePath);
    })();
    if (/-----BEGIN (?:[A-Z ]+ )?PRIVATE KEY-----/.test(data.toString("utf8"))) {
      throw new Error(`Refusing file containing private-key material: ${relativePath}`);
    }
    const compressed = deflateRawSync(data, { level: 9 });
    const name = Buffer.from(relativePath, "utf8");
    const checksum = crc32(data);
    const local = Buffer.concat([
      u32(0x04034b50), u16(20), u16(0x0800), u16(8), u16(fixedDosTime), u16(fixedDosDate),
      u32(checksum), u32(compressed.length), u32(data.length), u16(name.length), u16(0), name, compressed,
    ]);
    localParts.push(local);
    centralParts.push(Buffer.concat([
      u32(0x02014b50), u16((3 << 8) | 20), u16(20), u16(0x0800), u16(8), u16(fixedDosTime), u16(fixedDosDate),
      u32(checksum), u32(compressed.length), u32(data.length), u16(name.length), u16(0), u16(0), u16(0), u16(0),
      u32(normalizedMode(relativePath) << 16), u32(offset), name,
    ]));
    offset += local.length;
  }
  const central = Buffer.concat(centralParts);
  const end = Buffer.concat([
    u32(0x06054b50), u16(0), u16(0), u16(files.length), u16(files.length),
    u32(central.length), u32(offset), u16(0),
  ]);
  return Buffer.concat([...localParts, central, end]);
}

try {
  const files = await collectFiles();
  const generated = await generatedEntries();
  for (const required of ["package.json", "package-lock.json", ".env.example", "db/schema.sql", "scripts/init-db.mjs"]) {
    if (!files.includes(required)) throw new Error(`Required deployment file was excluded: ${required}`);
  }
  await mkdir(outputDirectory, { recursive: true });
  const archive = await buildZip(files, generated);
  await writeFile(temporaryPath, archive, { mode: 0o600 });
  await rename(temporaryPath, outputPath);
  const digest = createHash("sha256").update(archive).digest("hex");
  console.log(`Created ${path.relative(root, outputPath)} with ${files.length} files (${archive.length} bytes).`);
  console.log(`SHA-256 ${digest}`);
} catch (error) {
  await rm(temporaryPath, { force: true }).catch(() => undefined);
  console.error(`Packaging failed: ${error instanceof Error ? error.message : String(error)}`);
  process.exitCode = 1;
}
